### ISSUE TITLE
执行prdns报错

### ISSUE THREAD

**Issue by ted-dev-42** [arloan/prdns#4]
环境 ubuntu16.04  ruby2.6

Traceback (most recent call last):
        7: from /usr/local/bin/prdns:23:in `<main>'
        6: from /usr/local/bin/prdns:23:in `load'
        5: from /var/lib/gems/2.6.0/gems/prdns-0.1.0/exe/prdns:5:in `<top (required)>'
        4: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /var/lib/gems/2.6.0/gems/prdns-0.1.0/lib/prdns.rb:1:in `<top (required)>'
        1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- async/dns (LoadError)

**Comment by arloan** [comment]
@xcjiang Please check the output messages when you were installing the gem via `gem install prdns`, `prdns` depends on gem `async-dns`, which in return depends on gem `async-io`, it includes a native extension need to be compiled during the installation process. I guess there were some error message about it.

**Comment by ted-dev-42** [comment]
gem install 的时候并没有报错：

```
# gem install prdns
Fetching prdns-0.1.0.gem
Successfully installed prdns-0.1.0
Parsing documentation for prdns-0.1.0
Installing ri documentation for prdns-0.1.0
Done installing documentation for prdns after 0 seconds
1 gem installed
```

**Comment by arloan** [comment]
OK... maybe I forget to add dependencies for the Gem...- -b

**Comment by arloan** [comment]
OK, please **optionally** uninstall your already installed prdns version 0.1.0, then install the newest version 0.1.1, which fixed the missing dependencies problem.
