### ISSUE TITLE
What's the better way to deal with *root* issue?

### ISSUE THREAD

**Issue by ghost** [arloan/prdns#9]
If the Ruby/gem are not installed for root, and prdns was installed by this limited version of gem,
then prdns won't be able to listen on port 53.  

What's the better way to deal with this non-root 53 binding issue?  
Could you please suggesting one or two ways? Thanks!

**Comment by arloan** [comment]
It has nothing to do with how the gem was installed, just that listening to ports under 1024 needs root privilege.

setcap/authbind are possible solutions for this issue, see:
https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443/892391#892391
